# Generated by Django 3.0.3 on 2020-08-06 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_Info',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particaular image across whole application', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('size', models.IntegerField()),
                ('extension', models.CharField(max_length=16)),
                ('detail', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(300, 'Upload By Web'), (200, 'Upload By App')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
