# Generated by Django 3.0.3 on 2020-08-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_info',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='images_info',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='images_info',
            name='width',
            field=models.IntegerField(),
        ),
    ]
