# Generated by Django 3.0.3 on 2020-08-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isms', '0002_auto_20200805_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_info',
            name='type',
            field=models.IntegerField(choices=[(300, 'Upload By Web'), (200, 'Upload By App')]),
        ),
    ]
