# Generated by Django 3.0.3 on 2020-08-06 05:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms_Codes',
            fields=[
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('send_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Startup_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('type', models.CharField(default='supercar', max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='System_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('express', models.CharField(blank=True, help_text='Config Express', max_length=4096)),
                ('type', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=4096)),
                ('status', models.BooleanField(help_text='true for normal status')),
            ],
        ),
    ]
