# Generated by Django 3.0.3 on 2020-08-07 02:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup_img',
            name='id',
        ),
        migrations.RemoveField(
            model_name='system_config',
            name='id',
        ),
        migrations.AddField(
            model_name='sms_codes',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Left blank'),
        ),
        migrations.AddField(
            model_name='startup_img',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Left blank', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='system_config',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Left blank', primary_key=True, serialize=False),
        ),
    ]
