# Generated by Django 3.0.3 on 2020-08-04 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a car model name(e.g. Benz)', max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('state', models.BooleanField(help_text='Enter 0 or 1.(1=normal,0=delete)')),
            ],
        ),
        migrations.CreateModel(
            name='Car_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('mac', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('carModelId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Car_Model')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
