# Generated by Django 3.0.3 on 2020-08-05 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a car model name(e.g. Benz)', max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('state', models.BooleanField(help_text='Enter 0 or 1.(1=normal,0=delete)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('mac', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('carModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car_Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sms_Codes',
            fields=[
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('send_date', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Startup_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('type', models.CharField(default='supercar', max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='System_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('express', models.CharField(blank=True, max_length=4096)),
                ('type', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=4096)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Riding_Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.IntegerField()),
                ('duration', models.DurationField()),
                ('max_speed', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'ordering': ['car', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Riding_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('speed', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('electric', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, choices=[('s', 'Start'), ('e', 'End')], default='s', help_text='State of Car', max_length=1)),
                ('averageSpeed', models.IntegerField(default=0)),
                ('time', models.DateTimeField(help_text='riding time')),
                ('highSpeed', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'ordering': ['startDate', 'endDate'],
            },
        ),
        migrations.CreateModel(
            name='Riding_His_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Riding_Info')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Car_Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('result', models.CharField(max_length=50)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
