# Generated by Django 3.0.3 on 2020-08-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_user',
            options={'ordering': ['date', 'id'], 'permissions': (('can change state', 'Set car status'),)},
        ),
        migrations.AlterField(
            model_name='riding_statistics',
            name='duration',
            field=models.DurationField(help_text='Pleas enter valid format: [dd] [[hh:]mm:]ss'),
        ),
    ]
