# Generated by Django 3.0.3 on 2020-08-04 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms_Codes',
            fields=[
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('send_date', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Startup_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='System_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('express', models.CharField(blank=True, max_length=4096)),
                ('type', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=4096)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='car_model',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='car_user',
            options={'ordering': ['date', 'id']},
        ),
        migrations.RenameField(
            model_name='car_user',
            old_name='carModelId',
            new_name='carModel',
        ),
        migrations.RenameField(
            model_name='car_user',
            old_name='userId',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Riding_Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.IntegerField()),
                ('duration', models.DurationField()),
                ('max_speed', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'ordering': ['car', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Riding_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('speed', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('electric', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, choices=[('s', 'Start'), ('e', 'End')], default='s', help_text='State of Car', max_length=1)),
                ('averageSpeed', models.IntegerField(default=0)),
                ('time', models.DateTimeField(help_text='riding time')),
                ('highSpeed', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'ordering': ['startDate', 'endDate'],
            },
        ),
        migrations.CreateModel(
            name='Riding_His_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Riding_Info')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Images_Info',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particaular image across whole application', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('height', models.IntegerField(max_length=11)),
                ('width', models.IntegerField(max_length=11)),
                ('size', models.IntegerField(max_length=11)),
                ('extension', models.CharField(max_length=16)),
                ('detail', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('result', models.CharField(max_length=50)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
