# Generated by Django 3.0.3 on 2020-08-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200804_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images_Info',
        ),
    ]
