# Generated by Django 3.0.3 on 2020-08-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20200805_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_user',
            options={'ordering': ['date', 'id'], 'permissions': (('can_change_state', 'Set car states'),)},
        ),
    ]
