# Generated by Django 3.0.3 on 2020-08-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20200805_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riding_his_info',
            name='riding',
        ),
        migrations.RemoveField(
            model_name='riding_info',
            name='user',
        ),
        migrations.RemoveField(
            model_name='riding_statistics',
            name='car',
        ),
        migrations.DeleteModel(
            name='Sms_Codes',
        ),
        migrations.DeleteModel(
            name='Startup_Img',
        ),
        migrations.DeleteModel(
            name='System_Config',
        ),
        migrations.DeleteModel(
            name='Riding_His_Info',
        ),
        migrations.DeleteModel(
            name='Riding_Info',
        ),
        migrations.DeleteModel(
            name='Riding_Statistics',
        ),
    ]
