# Generated by Django 3.0.3 on 2020-08-07 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riding_Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('average_speed', models.IntegerField()),
                ('duration', models.DurationField(help_text='Pleas enter valid format: [dd] [[hh:]mm:]ss')),
                ('max_speed', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'ordering': ['car', 'date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Riding_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('speed', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('electric', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, choices=[('s', 'Start'), ('e', 'End')], default='s', help_text='State of Car', max_length=1)),
                ('averageSpeed', models.IntegerField(default=0)),
                ('time', models.DateTimeField(help_text='riding time')),
                ('highSpeed', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'ordering': ['startDate', 'endDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Riding_His_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('speed', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('electric', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, choices=[('s', 'Start'), ('e', 'End')], default='s', help_text='State of Car', max_length=1)),
                ('averageSpeed', models.IntegerField(default=0)),
                ('time', models.DateTimeField(help_text='riding time')),
                ('highSpeed', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car_User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
